# Generated by Django 2.2.1 on 2019-05-19 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='black_pieces_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='black_pieces_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='games',
            name='white_pieces_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='white_pieces_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
